### PR TITLE
Find more people, parties, factions

### PR DESCRIPTION
**Pull request by tammo0**
Improved queries to find more related and needed people, parties and factions

### CODE REVIEW

**Comment by alexabruck** [comment]
Many thanks for the improvements @tammo0 ! Just a minor change request for the sake of consistency:
In `src/optv_nel/wikidata/queries.p`y could you replace the raw wikidata identifiers with the strings from WIKIDATA_MAPPINGS? This helps with readability of our queries.
e.g. replace `wdt:P31` with `{INSTANCE_OF}`

**Comment by alexabruck** [comment]
Many thanks @tammo0 for the improvements :-)

**Comment by tammo0** [comment]
hey @alexabruck - sure, next time i will have this in mind. Sorry for the mess

**Comment by alexabruck** [comment]
Haha no mess at all, I'll add the mappings quickly!

**Comment by alexabruck** [comment]
@tammo0 
Question: Doesn't [Q11744698](https://www.wikidata.org/wiki/Q11744698) include all parliamentary groupings, not just German ones?

**Comment by tammo0** [comment]
Thats right. Some are foreign (like [Q217975](http://www.wikidata.org/entity/Q217975)) and some are just not good documented or labeled at wikidata. 
With this addition i aim to include [Q4316268](http://www.wikidata.org/entity/Q4316268) and [Q327591](http://www.wikidata.org/entity/Q327591) which are referenced in the people results. Not having these in the factions.json and/or parties.json, results in conflicts when importing media related to these factions or parties to openparilament.

As long as there is no media related to these misscraped parties/factions it doesn't affect the database of openparliament at all, so i see no problem having these miscategorized entities at our wikidata jsons.

The other way to deal with it would be something like i suggested in #28

**Comment by alexabruck** [comment]
That makes sense, thanks for clarifying!

**Comment by alexabruck** [comment]
Other option would be to add these 2 candidates manually, might be more explicit maybe?

**Comment by tammo0** [comment]
> Other option would be to add these 2 candidates manually, might be more explicit maybe?

was my first idea too, but with that we are more flexible in case something changes at wikidatas side now, i think.

**Pull request merged**
